select * from TB_TREINO

SELECT TRE.ID_TREINO, TRE.ALUNO_TREINO, TRE.NR_TREINO_ALUNO, TRD.ID_TREINO_DIA
FROM TB_TREINO AS TRE
INNER JOIN TB_TREINO_DIA AS TRD ON TRD.TREINO_TREINO_DIA = TRE.ID_TREINO
--INNER JOIN TB_EXERCICIO_TREINO AS EXT ON EXT.TREINO_DIA_EXERCICIO_TREINO = ID_TREINO_DIA

SELECT TRD.ID_TREINO_DIA, EXT.*
FROM TB_TREINO_DIA AS TRD
INNER JOIN TB_EXERCICIO_TREINO AS EXT ON EXT.TREINO_DIA_EXERCICIO_TREINO = TRD.ID_TREINO_DIA

select * from TB_TREINO_DIA
select * from TB_EXERCICIO_TREINO


SELECT TRE.ID_TREINO, TRE.ALUNO_TREINO, TRE.NR_TREINO_ALUNO, TRD.ID_TREINO_DIA
FROM TB_TREINO AS TRE
INNER JOIN TB_TREINO_DIA AS TRD ON TRD.TREINO_TREINO_DIA = TRE.ID_TREINO

SELECT
    ET.ID_EXERCICIO_TREINO,
    ET.TREINO_EXERCICIO_TREINO,
    ET.TREINO_DIA_EXERCICIO_TREINO,
    ET.EXERCICIO_EXERCICIO_TREINO,
    ET.SERIES_EXERCICIO_TREINO,
    ET.REPETICOES_EXERCICIO_TREINO,
    ET.TEMPO_EXERCICIO_TREINO,
    ET.CARGA_EXERCICIO_TREINO,
    ET.OBS_EXERCICIO_TREINO,
	TD.GRUPO_MUSCULAR_TREINO_DIA,
	EX.NOME_EXERCICIO,
	EX.DESCRICAO_EXERCICIO,
	EX.GRUPO_MUSCULAR
FROM
    TB_EXERCICIO_TREINO ET
INNER JOIN TB_TREINO_DIA TD ON ET.TREINO_DIA_EXERCICIO_TREINO = TD.ID_TREINO_DIA
INNER JOIN TB_EXERCICIO EX ON ET.EXERCICIO_EXERCICIO_TREINO = ID_EXERCICIO

WHERE ID_TREINO_DIA = 67



delete from  TB_TREINO


CREATE PROCEDURE SP_CONSULTA_TREINO_ATUAL
	@ID_ALUNO INT
AS
BEGIN
	DECLARE @ID_TREINO INT;
	SELECT TOP 1 @ID_TREINO = TRE.ID_TREINO, TRE.ID_TREINO, TRE.ALUNO_TREINO, TRE.NR_TREINO_ALUNO, TRD.ID_TREINO_DIA
	FROM TB_TREINO AS TRE
	INNER JOIN TB_TREINO_DIA AS TRD ON TRD.TREINO_TREINO_DIA = TRE.ID_TREINO
	ORDER BY DATA_INCLUSAO_TREINO DESC
	

	DECLARE @ID_TREINO INT;
	SET @ID_TREINO =

	SELECT
		ET.ID_EXERCICIO_TREINO,
		ET.TREINO_EXERCICIO_TREINO,
		ET.TREINO_DIA_EXERCICIO_TREINO,
		ET.EXERCICIO_EXERCICIO_TREINO,
		ET.SERIES_EXERCICIO_TREINO,
		ET.REPETICOES_EXERCICIO_TREINO,
		ET.TEMPO_EXERCICIO_TREINO,
		ET.CARGA_EXERCICIO_TREINO,
		ET.OBS_EXERCICIO_TREINO,
		TD.GRUPO_MUSCULAR_TREINO_DIA,
		EX.NOME_EXERCICIO,
		EX.DESCRICAO_EXERCICIO,
		EX.GRUPO_MUSCULAR
	FROM
		TB_EXERCICIO_TREINO ET
	INNER JOIN TB_TREINO_DIA TD ON ET.TREINO_DIA_EXERCICIO_TREINO = TD.ID_TREINO_DIA
	INNER JOIN TB_EXERCICIO EX ON ET.EXERCICIO_EXERCICIO_TREINO = ID_EXERCICIO	
	WHERE TREINO_TREINO_DIA = @ID_TREINO
END




ALTER PROCEDURE SP_CONSULTA_TREINO_ATUAL
	@ID_ALUNO INT
AS
BEGIN
	DECLARE @ID_TREINO INT;
	SELECT TOP 1 @ID_TREINO = TRE.ID_TREINO
	FROM TB_TREINO AS TRE
	INNER JOIN TB_TREINO_DIA AS TRD ON TRD.TREINO_TREINO_DIA = TRE.ID_TREINO
	ORDER BY DATA_INCLUSAO_TREINO DESC

	SELECT
		ET.ID_EXERCICIO_TREINO,
		ET.TREINO_EXERCICIO_TREINO,
		ET.TREINO_DIA_EXERCICIO_TREINO,
		ET.EXERCICIO_EXERCICIO_TREINO,
		ET.SERIES_EXERCICIO_TREINO,
		ET.REPETICOES_EXERCICIO_TREINO,
		ET.TEMPO_EXERCICIO_TREINO,
		ET.CARGA_EXERCICIO_TREINO,
		ET.OBS_EXERCICIO_TREINO,
		TD.GRUPO_MUSCULAR_TREINO_DIA,
		EX.NOME_EXERCICIO,
		EX.DESCRICAO_EXERCICIO,
		EX.GRUPO_MUSCULAR
	FROM
		TB_EXERCICIO_TREINO ET
	INNER JOIN TB_TREINO_DIA TD ON ET.TREINO_DIA_EXERCICIO_TREINO = TD.ID_TREINO_DIA
	INNER JOIN TB_EXERCICIO EX ON ET.EXERCICIO_EXERCICIO_TREINO = ID_EXERCICIO	
	WHERE TREINO_TREINO_DIA = @ID_TREINO
END
GO
EXEC SP_CONSULTA_TREINO_ATUAL 1



SELECT TRE.ID_TREINO, TRE.ALUNO_TREINO, TRE.NR_TREINO_ALUNO, TRD.ID_TREINO_DIA, TRD.GRUPO_MUSCULAR_TREINO_DIA
	FROM TB_TREINO AS TRE
	INNER JOIN TB_TREINO_DIA AS TRD ON TRD.TREINO_TREINO_DIA = TRE.ID_TREINO
	WHERE ID_TREINO = 46
	ORDER BY DATA_INCLUSAO_TREINO DESC


ALTER PROCEDURE SP_CONSULTA_TREINO_ATUAL
	@ID_ALUNO INT
AS
BEGIN
	DECLARE @ID_TREINO INT;
	SELECT TOP 1 @ID_TREINO = TRE.ID_TREINO
	FROM TB_TREINO AS TRE
	INNER JOIN TB_TREINO_DIA AS TRD ON TRD.TREINO_TREINO_DIA = TRE.ID_TREINO
	WHERE ALUNO_TREINO = @ID_ALUNO
	ORDER BY DATA_INCLUSAO_TREINO DESC

	SELECT TRE.ID_TREINO, TRE.ALUNO_TREINO, TRE.NR_TREINO_ALUNO, TRD.ID_TREINO_DIA, TRD.GRUPO_MUSCULAR_TREINO_DIA
	FROM TB_TREINO AS TRE
	INNER JOIN TB_TREINO_DIA AS TRD ON TRD.TREINO_TREINO_DIA = TRE.ID_TREINO
	WHERE ID_TREINO = @ID_TREINO
	ORDER BY DATA_INCLUSAO_TREINO DESC


	SELECT
		ET.ID_EXERCICIO_TREINO,
		ET.TREINO_EXERCICIO_TREINO,
		ET.TREINO_DIA_EXERCICIO_TREINO,
		ET.EXERCICIO_EXERCICIO_TREINO,
		ET.SERIES_EXERCICIO_TREINO,
		ET.REPETICOES_EXERCICIO_TREINO,
		ET.TEMPO_EXERCICIO_TREINO,
		ET.CARGA_EXERCICIO_TREINO,
		ET.OBS_EXERCICIO_TREINO,
		TD.GRUPO_MUSCULAR_TREINO_DIA,
		EX.NOME_EXERCICIO,
		EX.DESCRICAO_EXERCICIO,
		EX.GRUPO_MUSCULAR
	FROM
		TB_EXERCICIO_TREINO ET
	INNER JOIN TB_TREINO_DIA TD ON ET.TREINO_DIA_EXERCICIO_TREINO = TD.ID_TREINO_DIA
	INNER JOIN TB_EXERCICIO EX ON ET.EXERCICIO_EXERCICIO_TREINO = ID_EXERCICIO	
	WHERE TREINO_TREINO_DIA = @ID_TREINO
END
EXEC SP_CONSULTA_TREINO_ATUAL 1


SELECT
  ID_TREINO_DIA,
	TREINO_TREINO_DIA,
	GRUPO_MUSCULAR_TREINO_DIA
FROM 
	TB_TREINO AS TRE
INNER JOIN TB_TREINO_DIA AS TRD ON TRE.ID_TREINO = TRD.TREINO_TREINO_DIA
WHERE
	ID_TREINO = 46


select * from TB_DADOS_PESSOAIS_ALUNO

DECLARE @ID_ALUNO INT
SELECT
		A.ID_ALUNO,
		NOME_ALUNO,
		DATA_NASCIMENTO_ALUNO,
		SEXO_ALUNO,
		ALTURA_ALUNO,
		PESO_ALUNO,
		OBJETIVO_ALUNO,
		NIVEL_ATIVIDADE_ALUNO,
		FOTO_ALUNO,
		A.DATA_INCLUSAO,
		A.FLAG_ATIVO,
		ID_ANAMNESE_MEDICA,
		CONDICOES_MEDICAS_ALUNO,
		MEDICAMENTOS_ALUNO,
		RESTRICOES_ALIMENTARES_ALUNO,
		HISTORICO_EXERCICIOS_ALUNO,
		FREQUENCIA_CARDIACA_REPOUSO_ALUNO,
		PRESSAO_ARTERIAL_ALUNO,
		OUTRAS_OBSERVACOES_ALUNO,
		ID_DIMENSOES_CORPORAIS,
		DATA_MEDICAO_DIMENSOES_CORPORAIS,
		ALTURA_DIMENSOES_CORPORAIS,
		PESO_DIMENSOES_CORPORAIS,
		CIRCUNFERENCIA_BRACO_ESQ_DIMENSOES_CORPORAIS,
		CIRCUNFERENCIA_BRACO_DIR_DIMENSOES_CORPORAIS,
		CIRCUNFERENCIA_PERNA_ESQ_DIMENSOES_CORPORAIS,
		CIRCUNFERENCIA_PERNA_DIR_DIMENSOES_CORPORAIS,
		CIRCUNFERENCIA_PANTURRILHA_ESQ_DIMENSOES_CORPORAIS,
		CIRCUNFERENCIA_PANTURRILHA_DIR_DIMENSOES_CORPORAIS,
		CIRCUNFERENCIA_ABDOMINAL_DIMENSOES_CORPORAIS,
		CIRCUNFERENCIA_CINTURA_DIMENSOES_CORPORAIS,
		CIRCUNFERENCIA_QUADRIL_DIMENSOES_CORPORAIS,
		CIRCUNFERENCIA_PEITORAL_DIMENSOES_CORPORAIS,
		OUTRAS_MEDICOES_DIMENSOES_CORPORAIS,
		ID_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS,
		DATA_MEDICAO_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS,
		DOBRA_TRICEPS_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS,
		DOBRA_BICEPS_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS,
		DOBRA_SUBESCAPULAR_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS,
		DOBRA_SUPRAILIACA_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS,
		DOBRA_ABDOMEN_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS,
		DOBRA_AXILAR_MEDIA_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS,
		DOBRA_PERNA_MEDIA_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS,
		OUTRAS_MEDICOES_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS

    FROM TB_DADOS_PESSOAIS_ALUNO AS A
    INNER JOIN TB_ANAMNESE_MEDICA_ALUNO AS B ON A.ID_ALUNO = B.ID_ALUNO
    INNER JOIN TB_CIRCUNFERENCIAS_DIMENSOES_CORPORAIS AS C ON A.ID_ALUNO = C.ALUNO_ID_DIMENSOES_CORPORAIS
    INNER JOIN TB_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS AS D ON A.ID_ALUNO = D.ALUNO_ID_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS
    WHERE A.ID_ALUNO = 2
      AND C.DATA_INCLUSAO = (SELECT MIN(DATA_INCLUSAO) FROM TB_CIRCUNFERENCIAS_DIMENSOES_CORPORAIS WHERE ALUNO_ID_DIMENSOES_CORPORAIS = @ID_ALUNO)
      AND D.DATA_INCLUSAO = (SELECT MIN(DATA_INCLUSAO) FROM TB_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS WHERE ALUNO_ID_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS = @ID_ALUNO)
    ORDER BY C.DATA_INCLUSAO



	DECLARE @ID_TREINO INT;
	--SELECT TOP 1 @ID_TREINO = TRE.ID_TREINO
	SELECT *
	FROM TB_TREINO AS TRE
	INNER JOIN TB_TREINO_DIA AS TRD ON TRD.TREINO_TREINO_DIA = TRE.ID_TREINO
	INNER JOIN TB_DADOS_PESSOAIS_ALUNO AS DPA ON DPA.ID_ALUNO = TRE.ALUNO_TREINO
	WHERE ALUNO_TREINO = 1
	ORDER BY DATA_INCLUSAO_TREINO DESC


	SELECT DPA.NOME_ALUNO,TRE.NR_TREINO_ALUNO, TRE.MODELO_TREINO, TRE.FOCO_TREINO , TRD.ID_TREINO_DIA, TRD.GRUPO_MUSCULAR_TREINO_DIA
	FROM TB_TREINO AS TRE
	INNER JOIN TB_TREINO_DIA AS TRD ON TRD.TREINO_TREINO_DIA = TRE.ID_TREINO
	INNER JOIN TB_DADOS_PESSOAIS_ALUNO AS DPA ON DPA.ID_ALUNO = TRE.ALUNO_TREINO
	WHERE ID_TREINO = @ID_TREINO
	ORDER BY DATA_INCLUSAO_TREINO DESC



	SELECT
		TD.GRUPO_MUSCULAR_TREINO_DIA,
		EX.NOME_EXERCICIO,
		ET.SERIES_EXERCICIO_TREINO,
		ET.REPETICOES_EXERCICIO_TREINO,
		ET.TEMPO_EXERCICIO_TREINO,
		ET.CARGA_EXERCICIO_TREINO,
		ET.OBS_EXERCICIO_TREINO,
		EX.DESCRICAO_EXERCICIO
	FROM
		TB_EXERCICIO_TREINO ET
	INNER JOIN TB_TREINO_DIA TD ON ET.TREINO_DIA_EXERCICIO_TREINO = TD.ID_TREINO_DIA
	INNER JOIN TB_EXERCICIO EX ON ET.EXERCICIO_EXERCICIO_TREINO = ID_EXERCICIO	
	WHERE TREINO_TREINO_DIA = :ID_TREINO_DIA

	SELECT
		TD.GRUPO_MUSCULAR_TREINO_DIA,
		EX.NOME_EXERCICIO,
		ET.SERIES_EXERCICIO_TREINO,
		ET.REPETICOES_EXERCICIO_TREINO,
		ET.TEMPO_EXERCICIO_TREINO,
		ET.CARGA_EXERCICIO_TREINO,
		ET.OBS_EXERCICIO_TREINO,
		EX.DESCRICAO_EXERCICIO
	FROM
		TB_EXERCICIO_TREINO ET
	INNER JOIN TB_TREINO_DIA TD ON ET.TREINO_DIA_EXERCICIO_TREINO = TD.ID_TREINO_DIA
	INNER JOIN TB_EXERCICIO EX ON ET.EXERCICIO_EXERCICIO_TREINO = ID_EXERCICIO	
	WHERE TD.ID_TREINO_DIA = 113
