--DROP DATABASE SO_TREINOS
--CREATE DATABASE SO_TREINOS
--USE SO_TREINOS


CREATE TABLE TB_GRUPO_MUSCULAR
(
	ID_GRUPO_MUSCULAR INT IDENTITY PRIMARY KEY NOT NULL,
	NOME_GRUPO_MUSCULAR VARCHAR(50) NOT NULL,
	DATA_INCLUSAO_GRUPO_MUSCULAR DATETIME DEFAULT GETDATE() NOT NULL,
	FLAG_ATIVO BIT DEFAULT 1 NOT NULL
)

GO
/*
INSERT INTO GrupoMuscular (Nome) VALUES
(1, 'Peito'),
(2, 'Costas'),
(3, 'Ombros'),
(4, 'Braços'),
(5, 'Pernas'),
(6, 'Abdômen');
*/


CREATE TABLE TB_EXERCICIO
(
	ID_EXERCICIO INT IDENTITY PRIMARY KEY NOT NULL,
	NOME_EXERCICIO VARCHAR(100) NOT NULL,
	DESCRICAO_EXERCICIO TEXT,
	GRUPO_MUSCULAR INT FOREIGN KEY REFERENCES TB_GRUPO_MUSCULAR(ID_GRUPO_MUSCULAR),
	DATA_INCLUSAO_EXERCICIO DATETIME DEFAULT GETDATE() NOT NULL,
	FLAG_ATIVO BIT DEFAULT 1 NOT NULL
)


GO

CREATE TABLE TB_TREINO 
(
	ID_TREINO INT IDENTITY PRIMARY KEY NOT NULL,
	ALUNO_TREINO VARCHAR(255),
	NR_TREINO_ALUNO INT NOT NULL,
	--DATA_TREINO DATE,
	FOCO_TREINO TEXT,
	MODELO_TREINO VARCHAR(255), 
	OBS_TREINO TEXT,
	DATA_INCLUSAO_TREINO DATETIME DEFAULT GETDATE() NOT NULL,
	FLAG_ATIVO BIT DEFAULT 1 NOT NULL
)

GO

CREATE TABLE TB_TREINO_DIA
(
	ID_TREINO_DIA INT IDENTITY PRIMARY KEY NOT NULL,
	TREINO_TREINO_DIA INT FOREIGN KEY REFERENCES TB_TREINO(ID_TREINO) NOT NULL,
	--DATA_TREINO_DIA DATE NOT NULL,
	GRUPO_MUSCULAR_TREINO_DIA VARCHAR(255),
	DATA_INCLUSAO_TREINO_DIA DATETIME DEFAULT GETDATE() NOT NULL,
	FLAG_ATIVO BIT DEFAULT 1 NOT NULL
)

GO

CREATE TABLE TB_EXERCICIO_TREINO
(
	ID_EXERCICIO_TREINO INT IDENTITY PRIMARY KEY NOT NULL,
	TREINO_EXERCICIO_TREINO INT FOREIGN KEY REFERENCES TB_TREINO(ID_TREINO) NOT NULL,
	TREINO_DIA_EXERCICIO_TREINO INT FOREIGN KEY REFERENCES TB_TREINO_DIA(ID_TREINO_DIA) NOT NULL,
	EXERCICIO_EXERCICIO_TREINO INT FOREIGN KEY REFERENCES TB_EXERCICIO(ID_EXERCICIO) NOT NULL,
	SERIES_EXERCICIO_TREINO INT,
	REPETICOES_EXERCICIO_TREINO VARCHAR(10),
	TEMPO_EXERCICIO_TREINO NUMERIC(5,2),
	CARGA_EXERCICIO_TREINO NUMERIC(5,2),
	OBS_EXERCICIO_TREINO TEXT,
	DATA_INCLUSAO_EXERCICIO_TREINO DATETIME DEFAULT GETDATE() NOT NULL,
	FLAG_ATIVO BIT DEFAULT 1 NOT NULL
)

SELECT * FROM TB_EXERCICIO_TREINO
GO
