/*create database so_treinos
use so_treinos
*/
-- DROP DATABASE SO_TREINOS
--USE EXCLUISAO


CREATE TABLE TB_USUARIO
(
	ID_USUARIO INT IDENTITY PRIMARY KEY NOT NULL,
	NOME_USUARIO VARCHAR(200) NOT NULL,
	SENHA_USUARIO VARCHAR(20) NOT NULL,
	CHAVE_USUARIO VARCHAR(200) NOT NULL,
	DATA_INCLUSAO DATETIME DEFAULT GETDATE() NOT NULL,
	FLAG_ATIVO BIT DEFAULT 1 NOT NULL
)

GO

CREATE TABLE TB_DADOS_PESSOAIS_ALUNO 
(
    ID_ALUNO INT IDENTITY PRIMARY KEY NOT NULL,
    NOME_ALUNO VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO_ALUNO DATE NOT NULL,
    SEXO_ALUNO CHAR(1),
    ALTURA_ALUNO NUMERIC(5, 2),
    PESO_ALUNO NUMERIC(5, 2),
    OBJETIVO_ALUNO VARCHAR(255),
    NIVEL_ATIVIDADE_ALUNO INT,
    FOTO_ALUNO VARBINARY(MAX),
    DATA_INCLUSAO DATETIME DEFAULT GETDATE() NOT NULL,
    FLAG_ATIVO BIT DEFAULT 1 NOT NULL
)

GO

CREATE TABLE TB_ANAMNESE_MEDICA_ALUNO 
(
    ID_ANAMNESE_MEDICA INT IDENTITY PRIMARY KEY NOT NULL,
    ID_ALUNO INT FOREIGN KEY REFERENCES TB_DADOS_PESSOAIS_ALUNO(ID_ALUNO),
    CONDICOES_MEDICAS_ALUNO TEXT,
    MEDICAMENTOS_ALUNO TEXT,
    RESTRICOES_ALIMENTARES_ALUNO TEXT,
    HISTORICO_EXERCICIOS_ALUNO TEXT,
    FREQUENCIA_CARDIACA_REPOUSO_ALUNO INT,
    PRESSAO_ARTERIAL_ALUNO VARCHAR(20),
    OUTRAS_OBSERVACOES_ALUNO TEXT,
    DATA_INCLUSAO DATETIME DEFAULT GETDATE() NOT NULL,
    FLAG_ATIVO BIT DEFAULT 1 NOT NULL
)

GO

-- Tabela DIMENSOESCORPORAIS
CREATE TABLE TB_CIRCUNFERENCIAS_DIMENSOES_CORPORAIS 
(
    ID_DIMENSOES_CORPORAIS INT PRIMARY KEY,
    ALUNO_ID_DIMENSOES_CORPORAIS INT FOREIGN KEY REFERENCES TB_DADOS_PESSOAIS_ALUNO(ID_ALUNO),
    DATA_MEDICAO_DIMENSOES_CORPORAIS DATE,
    ALTURA_DIMENSOES_CORPORAIS NUMERIC(5,2),
    PESO_DIMENSOES_CORPORAIS NUMERIC(5,2),
    CIRCUNFERENCIA_BRACO_ESQ_DIMENSOES_CORPORAIS NUMERIC(5,2),
    CIRCUNFERENCIA_BRACO_DIR_DIMENSOES_CORPORAIS NUMERIC(5,2),
    CIRCUNFERENCIA_PERNA_ESQ_DIMENSOES_CORPORAIS NUMERIC(5,2),
    CIRCUNFERENCIA_PERNA_DIR_DIMENSOES_CORPORAIS NUMERIC(5,2),
	CIRCUNFERENCIA_PANTURRILHA_ESQ_DIMENSOES_CORPORAIS NUMERIC(5,2),
	CIRCUNFERENCIA_PANTURRILHA_DIR_DIMENSOES_CORPORAIS NUMERIC(5,2),
    CIRCUNFERENCIA_ABDOMINAL_DIMENSOES_CORPORAIS NUMERIC(5,2), -- Adicionando Circunferência Abdominal
	CIRCUNFERENCIA_CINTURA_DIMENSOES_CORPORAIS NUMERIC(5,2),
	CIRCUNFERENCIA_QUADRIL_DIMENSOES_CORPORAIS NUMERIC(5,2),
	CIRCUNFERENCIA_PEITORAL_DIMENSOES_CORPORAIS NUMERIC(5,2),
	OUTRAS_MEDICOES_DIMENSOES_CORPORAIS TEXT,
	DATA_INCLUSAO DATETIME DEFAULT GETDATE() NOT NULL,
	FLAG_ATIVO BIT DEFAULT 1 NOT NULL
)

GO

CREATE TABLE TB_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS
(
	ID_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS INT PRIMARY KEY,
    ALUNO_ID_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS INT FOREIGN KEY REFERENCES TB_DADOS_PESSOAIS_ALUNO(ID_ALUNO),
    DATA_MEDICAO_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS DATE,
	DOBRA_TRICEPS_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS NUMERIC(5,2),
	DOBRA_BICEPS_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS NUMERIC(5,2),
	DOBRA_SUBESCAPULAR_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS NUMERIC(5,2),
	DOBRA_SUPRAILIACA_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS NUMERIC(5,2),
	DOBRA_ABDOMEN_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS NUMERIC(5,2),
	DOBRA_AXILAR_MEDIA_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS NUMERIC(5,2),
	DOBRA_PERNA_MEDIA_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS NUMERIC(5,2),
	OUTRAS_MEDICOES_DOBRAS_CULTANEAS_DIMENSOES_CORPORAIS TEXT,
	DATA_INCLUSAO DATETIME DEFAULT GETDATE() NOT NULL,
	FLAG_ATIVO BIT DEFAULT 1 NOT NULL
)

GO


CREATE TABLE TB_GRUPO_MUSCULAR
(
	ID_GRUPO_MUSCULAR INT IDENTITY PRIMARY KEY NOT NULL,
	NOME_GRUPO_MUSCULAR VARCHAR(50) NOT NULL,
	DATA_INCLUSAO_GRUPO_MUSCULAR DATETIME DEFAULT GETDATE() NOT NULL,
	FLAG_ATIVO BIT DEFAULT 1 NOT NULL
)

GO
/*
INSERT INTO GrupoMuscular (Nome) VALUES
(1, 'Peito'),
(2, 'Costas'),
(3, 'Ombros'),
(4, 'Braços'),
(5, 'Pernas'),
(6, 'Abdômen');
*/


CREATE TABLE TB_EXERCICIO
(
	ID_EXERCICIO INT IDENTITY PRIMARY KEY NOT NULL,
	NOME_EXERCICIO VARCHAR(100) NOT NULL,
	DESCRICAO_EXERCICIO TEXT,
	GRUPO_MUSCULAR INT FOREIGN KEY REFERENCES TB_GRUPO_MUSCULAR(ID_GRUPO_MUSCULAR),
	DATA_INCLUSAO_EXERCICIO DATETIME DEFAULT GETDATE() NOT NULL,
	FLAG_ATIVO BIT DEFAULT 1 NOT NULL
)

GO

CREATE TABLE TB_TREINO 
(
	ID_TREINO INT IDENTITY PRIMARY KEY NOT NULL,
	ALUNO_TREINO VARCHAR(255),
	NR_TREINO_ALUNO INT NOT NULL,
	--DATA_TREINO DATE,
	FOCO_TREINO TEXT,
	MODELO_TREINO VARCHAR(255), 
	OBS_TREINO TEXT,
	DATA_INCLUSAO_TREINO DATETIME DEFAULT GETDATE() NOT NULL,
	FLAG_ATIVO BIT DEFAULT 1 NOT NULL
)

GO

CREATE TABLE TB_TREINO_DIA
(
	ID_TREINO_DIA INT IDENTITY PRIMARY KEY NOT NULL,
	TREINO_TREINO_DIA INT FOREIGN KEY REFERENCES TB_TREINO(ID_TREINO) NOT NULL,
	--DATA_TREINO_DIA DATE NOT NULL,
	GRUPO_MUSCULAR_TREINO_DIA VARCHAR(255),
	DATA_INCLUSAO_TREINO_DIA DATETIME DEFAULT GETDATE() NOT NULL,
	FLAG_ATIVO BIT DEFAULT 1 NOT NULL
)

GO

CREATE TABLE TB_EXERCICIO_TREINO
(
	ID_EXERCICIO_TREINO INT IDENTITY PRIMARY KEY NOT NULL,
	TREINO_EXERCICIO_TREINO INT FOREIGN KEY REFERENCES TB_TREINO(ID_TREINO) NOT NULL,
	TREINO_DIA_EXERCICIO_TREINO INT FOREIGN KEY REFERENCES TB_TREINO_DIA(ID_TREINO_DIA) NULL,
	EXERCICIO_EXERCICIO_TREINO INT FOREIGN KEY REFERENCES TB_EXERCICIO(ID_EXERCICIO) NOT NULL,
	SERIES_EXERCICIO_TREINO INT,
	REPETICOES_EXERCICIO_TREINO VARCHAR(10),
	TEMPO_EXERCICIO_TREINO NUMERIC(5,2),
	CARGA_EXERCICIO_TREINO NUMERIC(5,2),
	OBS_EXERCICIO_TREINO TEXT,
	DATA_INCLUSAO_EXERCICIO_TREINO DATETIME DEFAULT GETDATE() NOT NULL,
	FLAG_ATIVO BIT DEFAULT 1 NOT NULL
)

GO
SELECT * FROM TB_EXERCICIO_TREINO
GO
